alertmanager:
  alertmanagerSpec:
    route:
      group_by: ['alertname']
      receiver: telegram
      routes:
        - matchers:
            - severity="critical"
          receiver: slack
          continue: true
        - matchers:
            - severity="critical"
          receiver: telegram
        - matchers:
            - severity="warning"
          receiver: telegram
    receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            webhook_url: "${SLACK_WEBHOOK}"
      - name: telegram
        telegram_configs:
          - bot_token: "${TG_BOT_TOKEN}"
            chat_id: "${TG_CHAT_ID}"
            send_resolved: true
prometheus:
  prometheusSpec:
    additionalPrometheusRules:
      - name: vpn-rules
        groups:
          - name: vpn
            rules:
              - alert: HighErrorRate
                expr: |
                  sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
                for: 5m
                labels:
                  severity: page
                annotations:
                  summary: High error rate

