version: "3.9"       
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: vpn
      POSTGRES_DB: vpn
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vpn"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 5s
      retries: 5
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file: .env
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      retries: 5
    # Слушаем 80-й порт контейнера прямо на 80-м порту хоста,
    # чтобы домен открывался без указания порта.
    ports:
      - "80:80"

volumes:
  postgres-data:
