services:
# ──────────────────────────── infrastructure ────────────────────────────
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./certs:/etc/nginx/certs:ro"
      - "./logs/nginx:/var/log/nginx"
      - "./dist/main:/usr/share/nginx/html/main:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on: [backend, frontend]
    networks: [app]

# ──────────────────────────── application ───────────────────────────────
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: vpn
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 5s
      retries: 5
    networks: [app]

  hanko-migrate:
    image: ghcr.io/teamhanko/hanko:latest
    command: ["migrate", "up"]
    volumes:
      - ./config.yaml:/etc/hanko/config.yaml:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks: [app]
 hanko:
  image: ghcr.io/teamhanko/hanko:latest
  ports:
    - "8000:8000"          # наружу → localhost:8000
  command: ["serve", "--listen", "0.0.0.0:8000"]   # ← главное
  environment:
      HANKO_JWT_SECRET: ${HANKO_JWT_SECRET:-changeme}
      HANKO_WEBAUTHN_RELYING_PARTY_ID: ${HANKO_WEBAUTHN_RELYING_PARTY_ID:-localhost}
      HANKO_WEBAUTHN_RELYING_PARTY_ORIGINS: ${HANKO_WEBAUTHN_RELYING_PARTY_ORIGINS:-http://localhost:5173,http://localhost:80,https://localhost}
    volumes:
      - ./config.yaml:/etc/hanko/config.yaml:ro
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    networks: [app]

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - ./.env
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_FILE_ENABLED: ${LOG_FILE_ENABLED:-true}
      PINO_PRETTY_DISABLE: ${PINO_PRETTY_DISABLE:-false}
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy &&
             node dist/index.js"
    healthcheck:
      test: ["CMD-SHELL","curl -sf http://localhost:4000/healthz | grep OK || exit 1"]
      interval: 10s
      retries: 5
    volumes:
      - ./logs/app:/app/logs
    networks: [app]
    ports:
      - 4000:4000


  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE_URL
    env_file: ./.env
    depends_on:
      backend:
        condition: service_started
    networks: [app]

volumes:
  postgres-data:

networks:
  app:
