version: "3.9"       
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: vpn
      POSTGRES_DB: vpn
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vpn"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      DATABASE_URL: postgres://vpn:vpn@postgres:5432/vpn
      JWT_SECRET: ${JWT_SECRET}   # пусть берёт из .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .                 
      dockerfile: src/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres-data:
