FROM node:20-alpine as builder
WORKDIR /app
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
COPY . .
RUN corepack enable && pnpm i --frozen-lockfile && pnpm run build
FROM nginx:1.27-alpine
COPY docker/frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
