version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vpn
      POSTGRES_PASSWORD: vpn
      POSTGRES_DB: vpn
    ports:
      - '5432:5432'

  backend:
    build: ./server
    environment:
      DATABASE_URL: postgres://vpn:vpn@postgres:5432/vpn
      JWT_SECRET: change_this_default_secret_at_least_32_chars!
    depends_on:
      - postgres
    ports:
      - '4000:4000'

  frontend:
    build: ./src
    ports:
      - '5173:80'
    depends_on:
      - backend
