app = "vpn-api-staging"
primary_region = "ams"
[build]
  image = "ghcr.io/jah0x/vpn-api:latest"

[env]
  DATABASE_URL = "postgres://vpn:vpn@db.internal:5432/vpn"
  JWT_SECRET = "REPLACE_ME"
  STRIPE_KEY = "REPLACE_ME"

[deploy]
  release_command = "npm run migrate"
