apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpn-api
  template:
    metadata:
      labels:
        app: vpn-api
    spec:
      containers:
        - name: vpn-api
          image: ghcr.io/jah0x/vpn-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vpn-secrets
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vpn-secrets
                  key: jwt_secret
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: vpn-secrets
                  key: stripe_key
          readinessProbe:
            httpGet:
              path: /metrics
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vpn-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpn-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
