openapi: 3.0.0
info:
  title: VPN Service API
  version: 1.1.0
servers:
  - url: http://localhost:4000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserLogin:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    Tokens:
      type: object
      properties:
        access:
          type: string
        refresh:
          type: string
    Vpn:
      type: object
      properties:
        id:
          type: string
        ownerId:
          type: string
        name:
          type: string
        tariffId:
          type: string
    VpnCreateRequest:
      type: object
      required: [name, tariffId]
      properties:
        name:
          type: string
        tariffId:
          type: string
security:
  - bearerAuth: []
paths:
  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Tokens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /api/auth/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
      responses:
        '200':
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
  /api/vpn:
    get:
      summary: List VPNs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: VPN list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vpn'
    post:
      summary: Create VPN
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VpnCreateRequest'
      responses:
        '201':
          description: Created VPN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vpn'
  /api/vpn/{id}:
    patch:
      summary: Update VPN
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VpnCreateRequest'
      responses:
        '200':
          description: Updated VPN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vpn'
    delete:
      summary: Delete VPN
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted VPN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vpn'
  /api/config:
    get:
      summary: Download VPN config
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Config file
          content:
            application/json:
              schema:
                type: object
        '402':
          description: Subscription required
  /api/admin/config-template:
    get:
      summary: Get config template
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Template JSON
          content:
            application/json:
              schema:
                type: object
    put:
      summary: Update config template
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Updated template
          content:
            application/json:
              schema:
                type: object

  /metrics:
    get:
      summary: Prometheus metrics
      description: Exposes Prometheus metrics for scraping.
      responses:
        '200':
          description: Metrics output
          content:
            text/plain:
              schema:
                type: string

  /api/billing/checkout:
    post:
      summary: Start Stripe Checkout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan:
                  type: string
                  enum: [basic, pro, team]
      responses:
        '200':
          description: Checkout URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string

  /api/billing/webhook:
    post:
      summary: Stripe webhook
      responses:
        '200':
          description: Received
          content:
            application/json:
              schema:
                type: object
