name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - run: corepack prepare pnpm@9.2.0 --activate
      - run: |
          if [ -f yarn.lock ] || [ -e .pnp.cjs ]; then
            echo "❌ forbidden lock-file"; exit 1;
          fi
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec tsc -b apps/${{ matrix.service }}
      - run: pnpm exec eslint "apps/${{ matrix.service }}/src/**/*.{ts,tsx}" --max-warnings=0
      - run: npx openapi-cli validate apps/server/openapi.yaml
